In [4]:
import numpy as np
from scipy.stats import multivariate_normal

X = np.loadtxt('data.txt',delimiter=',')
K = 4
#print norm.pdf(data[0],loc=0,scale=0.1)
X = np.asarray(X)
X_shape = np.shape(X)
N = X_shape[0]
d = X_shape[1]        
logLikelihoods = []
K = K
phi = np.ones((N,K))
pi = np.random.normal((1,K))
pi = pi/np.sum(pi)
mu = np.random.normal(size=(K,d))
sgm = np.random.uniform(size=(K,d,d))

print sgm
for i in range(K):
    sgm[i] = sgm[i].dot(sgm[i].T)
print sgm

#print multivariate_normal.logpdf(X,mu[1],sgm[1])
#mj = 0
#nj = np.sum(phi,axis=0)

#for i in range(len(X)):
#    for j in range(K):
#        mu[j] += 1/nj * phi[i][j] * X[i]

#print mu

[[[ 0.96807003  0.78989445]
  [ 0.8696877   0.1107322 ]]

 [[ 0.26100839  0.45041074]
  [ 0.47306504  0.2743308 ]]

 [[ 0.46984475  0.42733223]
  [ 0.19182933  0.23865411]]

 [[ 0.95151851  0.68188119]
  [ 0.11003421  0.27904341]]]
[[[ 1.56109282  0.92938535]
  [ 0.92938535  0.76861832]]

 [[ 0.27099522  0.24703548]
  [ 0.24703548  0.29904792]]

 [[ 0.40336692  0.19211459]
  [ 0.19211459  0.09375427]]

 [[ 1.37034942  0.29497404]
  [ 0.29497404  0.08997275]]]
